// ============================================================
// FraudSentry — internal-consistency checks on a receipt
//
// A faked receipt is usually made by editing ONE figure on a genuine
// screenshot. Two things an editor commonly forgets to keep consistent:
//   1. Arithmetic — the amount, the fee and the total must reconcile
//      (GCash bank transfer: "1,000.00 / +Fee 10.00 / Total ₱1,010.00").
//   2. Time — a receipt cannot be dated after the moment it is checked.
// Both are judged from the raw OCR text of ALL passes, and only when the
// reading is stable across passes, so a single OCR misread can't raise them.
// ============================================================

const MONEY_RE = /(\d{1,3}(?:[, ]\d{3})+\.\d{2}|\d+\.\d{2})/g;
const toNum = (s: string) => parseFloat(s.replace(/[, ]/g, ''));
const round2 = (n: number) => Math.round(n * 100) / 100;

/** Last money value on a line after its label (e.g. "Total ₱ 1,010.00"). */
function lastMoney(line: string): number | null {
  const all = [...line.matchAll(MONEY_RE)].map(m => toNum(m[1])).filter(n => !isNaN(n));
  return all.length ? all[all.length - 1] : null;
}

/** Fee and total as printed on ONE OCR pass. A waived fee ("PHP 15.00 FREE") counts as 0. */
export function readFeeAndTotal(text: string): { fee: number | null; total: number | null } {
  let fee: number | null = null, total: number | null = null;
  for (const raw of (text || '').split('\n')) {
    const line = raw.replace(/\s+/g, ' ').trim();
    // "+Fee", "tFee" (OCR of "+Fee"), "Transaction fee", "Convenience Fee (2%)"
    if (fee == null && /(?:^|[\s+t])fee\b/i.test(line) && !/fee\s*(?:may|will|is|of\s+up)/i.test(line)) {
      fee = /\b(free|waived)\b/i.test(line) ? 0 : lastMoney(line.replace(/\(\s*\d+(?:\.\d+)?\s*%\s*\)/, ''));
    }
    if (total == null && /^total\b(?!\s*(?:balance|savings|points))/i.test(line)) total = lastMoney(line);
  }
  return { fee, total };
}

function stableValue(vals: (number | null)[]): number | null {
  const read = vals.filter((v): v is number => v != null);
  if (!read.length) return null;
  const counts = new Map<number, number>();
  for (const v of read) counts.set(v, (counts.get(v) || 0) + 1);
  const [best, n] = [...counts.entries()].sort((a, b) => b[1] - a[1])[0];
  // with several passes, require the value to be read the same way at least twice
  return read.length >= 2 && n < 2 ? null : best;
}

/** Every money value printed anywhere on the receipt (all passes). */
function moneyValues(texts: string[]): Set<number> {
  const s = new Set<number>();
  for (const t of texts) for (const m of t.matchAll(MONEY_RE)) { const v = toNum(m[1]); if (!isNaN(v)) s.add(round2(v)); }
  return s;
}

export interface AmountReconciliation {
  status: 'consistent' | 'mismatch' | 'unknown';
  amount: number | null;
  fee: number | null;
  total: number | null;
  detail: string;
}

const php = (n: number) => `₱${n.toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

/**
 * Does amount + fee = total?  `amount` is the parser's principal amount.
 * 'unknown' whenever the receipt doesn't print all three, or OCR is unstable.
 */
export function reconcileAmounts(texts: string[], amount: number | null): AmountReconciliation {
  const list = (texts || []).filter(t => t && t.trim());
  const reads = list.map(readFeeAndTotal);
  const fee = stableValue(reads.map(r => r.fee));
  const total = stableValue(reads.map(r => r.total));
  const unknown = { status: 'unknown' as const, amount, fee, total, detail: '' };
  if (amount == null || fee == null || total == null || total <= 0) return unknown;

  const expected = round2(total - fee);
  if (Math.abs(round2(amount) - expected) < 0.005) {
    return { status: 'consistent', amount, fee, total,
      detail: `The amount (${php(amount)}) plus the fee (${php(fee)}) equals the total shown (${php(total)}).` };
  }
  // Parser took the total as the amount, and the true principal is printed: not an anomaly.
  if (round2(amount) === round2(total) && moneyValues(list).has(expected)) return unknown;

  return { status: 'mismatch', amount, fee, total,
    detail: `The figures on this receipt do not add up: amount ${php(amount)} + fee ${php(fee)} = ${php(round2(amount + fee))}, but the total shown is ${php(total)}. A genuine receipt is generated by the app and always reconciles — a mismatch usually means one figure was edited. Check the payment inside your own account.` };
}

/**
 * The parser's principal amount, corrected when it picked the total by mistake
 * (e.g. a load purchase "Amount" row missed by OCR, "Convenience Fee 20.00 / Total 1,020.00"
 * → principal 1,000.00, which is printed elsewhere on the receipt).
 */
export function correctPrincipal(texts: string[], amount: number | null): number | null {
  if (amount == null) return amount;
  const list = (texts || []).filter(t => t && t.trim());
  const reads = list.map(readFeeAndTotal);
  const fee = stableValue(reads.map(r => r.fee));
  const total = stableValue(reads.map(r => r.total));
  if (fee == null || total == null || fee <= 0 || round2(amount) !== round2(total)) return amount;
  const expected = round2(total - fee);
  return expected > 0 && moneyValues(list).has(expected) ? expected : amount;
}

// ── Date sanity ───────────────────────────────────────────────────────────
const MONTHS = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'];

/**
 * Parse the receipt's date (+ optional time) as PH local time.
 * Returns null when unreadable, and 'invalid' for impossible dates (e.g. "Feb 30 2026").
 * Numeric dates are read as month/day/year (PH apps' convention).
 */
export function parseReceiptDate(date: string | null, time?: string | null): Date | 'invalid' | null {
  if (!date) return null;
  const d = date.trim().toLowerCase();
  let y: number, mo: number, day: number;
  let m: RegExpMatchArray | null;
  if ((m = d.match(/^([a-z]{3})[a-z]*\.?\s+(\d{1,2})(?:st|nd|rd|th)?\s*,?\s*(\d{4})$/))) {
    mo = MONTHS.indexOf(m[1]); day = +m[2]; y = +m[3];
  } else if ((m = d.match(/^(\d{1,2})\s+([a-z]{3})[a-z]*\.?\s*,?\s*(\d{4})$/))) {
    mo = MONTHS.indexOf(m[2]); day = +m[1]; y = +m[3];
  } else if ((m = d.match(/^(\d{4})-(\d{2})-(\d{2})$/))) {
    y = +m[1]; mo = +m[2] - 1; day = +m[3];
  } else if ((m = d.match(/^(\d{1,2})[/\-.](\d{1,2})[/\-.](\d{2,4})$/))) {
    mo = +m[1] - 1; day = +m[2]; y = +m[3] < 100 ? 2000 + +m[3] : +m[3];
  } else return null;
  if (mo < 0 || mo > 11 || day < 1 || y < 2000 || y > 2100) return 'invalid';

  let hh = 0, mm = 0;
  const t = time?.trim().toLowerCase().match(/^(\d{1,2}):(\d{2})(?::\d{2})?\s*(am|pm)?$/);
  if (t) {
    hh = +t[1]; mm = +t[2];
    if (t[3] === 'pm' && hh < 12) hh += 12;
    if (t[3] === 'am' && hh === 12) hh = 0;
    if (hh > 23 || mm > 59) return 'invalid';
  }
  // PH is UTC+8 all year (no DST)
  const out = new Date(Date.UTC(y, mo, day, hh - 8, mm));
  const back = new Date(out.getTime() + 8 * 3600_000);
  if (back.getUTCDate() !== day || back.getUTCMonth() !== mo) return 'invalid'; // e.g. Feb 30
  return out;
}

export interface DateCheck {
  status: 'ok' | 'future' | 'invalid' | 'unknown';
  detail: string;
}

/**
 * A receipt dated after "now" cannot be genuine. A 12-hour grace absorbs
 * device clock / time-zone differences, and a date-only receipt is compared
 * by day, so ordinary use never trips it.
 */
export function checkReceiptDate(date: string | null, time: string | null, now: Date = new Date()): DateCheck {
  const parsed = parseReceiptDate(date, time);
  if (parsed == null) return { status: 'unknown', detail: '' };
  if (parsed === 'invalid') {
    return { status: 'invalid',
      detail: `The date/time on this receipt ("${[date, time].filter(Boolean).join(' ')}") is not a real calendar date or clock time. Apps generate these automatically, so an impossible value suggests the text was typed in by hand — unless it is an OCR misread (use "Correct text" to fix it).` };
  }
  const graceMs = (time ? 12 : 36) * 3600_000;
  if (parsed.getTime() - now.getTime() > graceMs) {
    return { status: 'future',
      detail: `This receipt is dated ${[date, time].filter(Boolean).join(' ')} — after the moment it was checked. A real transaction cannot happen in the future; the date was most likely edited, or the receipt was prepared in advance. Do not accept it as proof of payment.` };
  }
  return { status: 'ok', detail: '' };
}
