// ============================================================
// FraudSentry — PDF Investigation Report Generator
// Builds a professional, evidence-backed PDF from a REAL scan result.
// Every value printed comes from the stored analysis — nothing is
// invented at report time.
// ============================================================

import { jsPDF } from 'jspdf';
import { ImageScanResult, MessageScanResult } from '../types';
import { RISK_META } from '../utils/helpers';

const NAVY = '#0f172a';
const BLUE = '#2563eb';
const MUTE = '#64748b';

function header(doc: jsPDF, title: string, caseId: string) {
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 26, 'F');
  doc.setTextColor('#ffffff'); doc.setFont('helvetica', 'bold'); doc.setFontSize(15);
  doc.text('FraudSentry', 14, 13);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor('#93c5fd');
  doc.text('Fraud Verification & Scam Intelligence Platform', 14, 19);
  doc.setFontSize(8); doc.setTextColor('#cbd5e1');
  doc.text(caseId, 196, 13, { align: 'right' });
  doc.text(new Date().toLocaleString('en-PH'), 196, 19, { align: 'right' });
  doc.setTextColor(NAVY); doc.setFont('helvetica', 'bold'); doc.setFontSize(13);
  doc.text(title, 14, 38);
  doc.setDrawColor(BLUE); doc.setLineWidth(0.6); doc.line(14, 41, 196, 41);
}

function riskBanner(doc: jsPDF, y: number, level: string, label: string, scorePct: number) {
  const m = RISK_META[level as keyof typeof RISK_META];
  const rgb = hexToRgb(m.hex);
  doc.setFillColor(rgb.r, rgb.g, rgb.b);
  doc.roundedRect(14, y, 182, 16, 2, 2, 'F');
  doc.setTextColor('#ffffff'); doc.setFont('helvetica', 'bold'); doc.setFontSize(11);
  doc.text(`${m.label.toUpperCase()}  ·  ${scorePct}%`, 18, y + 7);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5);
  doc.text(label, 18, y + 12.5);
  return y + 22;
}

function hexToRgb(hex: string) {
  const n = parseInt(hex.slice(1), 16);
  return { r: (n >> 16) & 255, g: (n >> 8) & 255, b: n & 255 };
}

function sectionTitle(doc: jsPDF, y: number, text: string) {
  doc.setTextColor(BLUE); doc.setFont('helvetica', 'bold'); doc.setFontSize(10);
  doc.text(text, 14, y);
  return y + 5;
}

function kv(doc: jsPDF, y: number, k: string, v: string) {
  doc.setTextColor(MUTE); doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5);
  doc.text(k, 16, y);
  doc.setTextColor(NAVY); doc.setFont('helvetica', 'bold');
  doc.text(v || '—', 70, y);
  return y + 5.5;
}

// jsPDF's built-in Helvetica only covers the WinAnsi character set: "₱" and the
// "•" used in masked names/numbers would print as garbage. Map them to ASCII.
function pdfSafe(t: string): string {
  return t.replace(/₱\s?/g, 'PHP ').replace(/[•●∙]/g, '*');
}

function footer(doc: jsPDF) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setDrawColor(220); doc.setLineWidth(0.3); doc.line(14, 285, 196, 285);
    doc.setTextColor(MUTE); doc.setFont('helvetica', 'normal'); doc.setFontSize(7);
    doc.text('Generated by FraudSentry — an evidence-based risk assessment, not a legal or bank-certified determination of fraud.', 14, 290);
    doc.text(`Page ${i} of ${pages}`, 196, 290, { align: 'right' });
  }
}

export function generateImageReport(scan: ImageScanResult) {
  const doc = new jsPDF();
  const caseId = `CASE-${scan.id.slice(-8).toUpperCase()}`;
  header(doc, 'Transaction Authenticity Report', caseId);
  let y = 48;
  y = riskBanner(doc, y, scan.riskLevel, scan.legitimacyLabel, Math.round(scan.riskScore * 100));

  // evidence preview
  if (scan.previewDataUrl) {
    try {
      const props = doc.getImageProperties(scan.previewDataUrl);
      const w = 52, h = Math.min(70, (props.height / props.width) * w);
      doc.addImage(scan.previewDataUrl, 'JPEG', 144, y, w, h);
    } catch { /* skip */ }
  }

  y = sectionTitle(doc, y, 'Evidence Source');
  y = kv(doc, y, 'File name', scan.filename);
  y = kv(doc, y, 'Detected institution', scan.source);
  y = kv(doc, y, 'Assessment confidence', `${scan.confidence}%`);
  y = kv(doc, y, 'Analyzed at', new Date(scan.scannedAt).toLocaleString('en-PH'));
  y += 3;

  y = sectionTitle(doc, y, 'Extracted Transaction Data (OCR)');
  const e = scan.extracted;
  y = kv(doc, y, 'Amount', e.amount != null ? `PHP ${e.amount.toLocaleString('en-PH', { minimumFractionDigits: 2 })}` : 'Not detected');
  y = kv(doc, y, 'Reference / Txn no.', e.referenceNo || e.transactionId || 'Not detected');
  y = kv(doc, y, 'Date / Time', [e.date, e.time].filter(Boolean).join(' ') || 'Not detected');
  y = kv(doc, y, 'Sender', pdfSafe(e.senderName || 'Not detected'));
  y = kv(doc, y, 'Receiver', pdfSafe(e.receiverName || 'Not detected'));
  y = kv(doc, y, 'Receiver No.', pdfSafe(e.receiverContact || 'Not detected'));
  y = kv(doc, y, 'OCR engine', `${scan.ocr.engine} · ${scan.ocr.confidence}% confidence`);
  y += 3;

  y = sectionTitle(doc, y, 'Image Forensics');
  const f = scan.forensics;
  y = kv(doc, y, 'Container (header)', f.sniffType);
  y = kv(doc, y, 'Dimensions', `${f.width}x${f.height} (${f.aspectRatio})`);
  y = kv(doc, y, 'EXIF metadata', f.hasExif ? 'present' : 'absent');
  y = kv(doc, y, 'Editor signature', f.editorSoftware || 'none');
  y = kv(doc, y, 'Error Level Analysis', `mean ${f.elaScore}/100, ${f.elaHotspotPct}% hotspots`);
  y += 4;

  // How the final score was formed — the Random Forest is half of it.
  if (scan.forestAnalysis) {
    const fa = scan.forestAnalysis;
    y = sectionTitle(doc, y, 'How the Risk Score Was Computed');
    y = kv(doc, y, 'Rule-based findings score', `${Math.round((scan.heuristicScore ?? 0) * 100)}%`);
    y = kv(doc, y, 'Random Forest probability', `${Math.round(fa.probability * 100)}% (${fa.votesFraud} of ${fa.totalTrees} trees voted fraudulent)`);
    y = kv(doc, y, 'Final risk (50% + 50%)', `${Math.round(scan.riskScore * 100)}%`);
    y = kv(doc, y, 'Forest training data', fa.datasetSource === 'demo' ? 'seeded demonstration dataset (not real collected evidence)' : 'uploaded labelled evidence dataset');
    y += 3;
  }

  y = sectionTitle(doc, y, 'Findings (weights within the rule-based score)');
  doc.setFontSize(8);
  for (const fd of scan.findings) {
    if (y > 268) { doc.addPage(); y = 20; }
    const rgb = hexToRgb(RISK_META[fd.severity].hex);
    doc.setFillColor(fd.passed ? 16 : rgb.r, fd.passed ? 185 : rgb.g, fd.passed ? 129 : rgb.b);
    doc.circle(16, y - 1.2, 1.1, 'F');
    doc.setTextColor(NAVY); doc.setFont('helvetica', 'bold');
    doc.text(`${fd.label}${fd.passed ? '' : `  (+${Math.round(fd.weight * 100)}% rule weight)`}`, 20, y);
    y += 4;
    doc.setTextColor(MUTE); doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(pdfSafe(fd.detail), 174);
    doc.text(lines, 20, y); y += lines.length * 3.6 + 2;
  }

  if (y > 250) { doc.addPage(); y = 20; }
  y = sectionTitle(doc, y + 2, 'Recommended Action');
  doc.setTextColor(NAVY); doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5);
  const rec = doc.splitTextToSize(scan.recommendedAction, 180);
  doc.text(rec, 16, y);
  y += rec.length * 4 + 3;

  if (scan.actionPlan && scan.actionPlan.length) {
    if (y > 250) { doc.addPage(); y = 20; }
    y = sectionTitle(doc, y, 'What To Do Next');
    doc.setFontSize(8.5);
    scan.actionPlan.forEach((step, i) => {
      const lines = doc.splitTextToSize(`${i + 1}. ${pdfSafe(step)}`, 178);
      if (y + lines.length * 4 > 280) { doc.addPage(); y = 20; }
      doc.text(lines, 16, y);
      y += lines.length * 4 + 1.5;
    });
  }

  footer(doc);
  doc.save(`${caseId}-transaction-report.pdf`);
}

export function generateMessageReport(scan: MessageScanResult) {
  const doc = new jsPDF();
  const caseId = `CASE-${scan.id.slice(-8).toUpperCase()}`;
  header(doc, 'Fraud Message Analysis Report', caseId);
  let y = 48;
  y = riskBanner(doc, y, scan.threatLevel, `${scan.scamType} · ${scan.platform}`, Math.round(scan.riskScore * 100));

  y = sectionTitle(doc, y, 'Summary');
  doc.setTextColor(NAVY); doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5);
  const ex = doc.splitTextToSize(scan.explanation, 180); doc.text(ex, 16, y); y += ex.length * 4 + 4;

  y = sectionTitle(doc, y, 'Analyzed Message');
  doc.setFillColor(245, 247, 250); doc.setDrawColor(225);
  const msgLines = doc.splitTextToSize(pdfSafe(scan.sourceText.slice(0, 1200)), 176);
  const boxH = Math.min(60, msgLines.length * 3.8 + 6);
  doc.roundedRect(14, y, 182, boxH, 2, 2, 'FD');
  doc.setTextColor(MUTE); doc.setFontSize(7.6); doc.text(msgLines, 18, y + 5); y += boxH + 5;

  if (scan.flags.length) {
    y = sectionTitle(doc, y, 'Detected Fraud Signals');
    doc.setFontSize(8);
    for (const fl of scan.flags) {
      if (y > 268) { doc.addPage(); y = 20; }
      const rgb = hexToRgb(RISK_META[fl.severity].hex);
      doc.setFillColor(rgb.r, rgb.g, rgb.b); doc.circle(16, y - 1.2, 1.1, 'F');
      doc.setTextColor(NAVY); doc.setFont('helvetica', 'bold');
      doc.text(`"${pdfSafe(fl.keyword)}"  (+${Math.round(fl.weight * 100)}%)`, 20, y); y += 4;
      doc.setTextColor(MUTE); doc.setFont('helvetica', 'normal');
      const ls = doc.splitTextToSize(fl.reason, 174); doc.text(ls, 20, y); y += ls.length * 3.6 + 2;
    }
  }

  if (scan.links.length) {
    if (y > 250) { doc.addPage(); y = 20; }
    y = sectionTitle(doc, y + 2, 'Link Analysis');
    doc.setFontSize(8);
    for (const lk of scan.links) {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.setTextColor(BLUE); doc.setFont('helvetica', 'bold'); doc.text(lk.url.slice(0, 80), 16, y); y += 4;
      doc.setTextColor(MUTE); doc.setFont('helvetica', 'normal');
      const ls = doc.splitTextToSize(lk.reason, 176); doc.text(ls, 16, y); y += ls.length * 3.6 + 2;
    }
  }

  if (y > 250) { doc.addPage(); y = 20; }
  y = sectionTitle(doc, y + 2, 'Recommended Actions');
  doc.setTextColor(NAVY); doc.setFont('helvetica', 'normal'); doc.setFontSize(8.5);
  for (const a of scan.recommendedActions) {
    const ls = doc.splitTextToSize('•  ' + a, 178); doc.text(ls, 16, y); y += ls.length * 4 + 1;
  }

  footer(doc);
  doc.save(`${caseId}-message-report.pdf`);
}
